<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="frontEnd/app/js_depl/styles.css" />
    <meta name="viewport" content="width=device-width, initial-scale=.5">
    <meta name="keywords" content="Коллекционные монеты, памятные монеты, монеты,10р">
    <meta name="description" content="Коллекционные монеты">
</head>
<title> Коллекционер </title>
<body>
   <div class="container layout">
      <div class="row">
          <div id = "coinEntrance" class="col-xs-12"></div>
      </div>
   </div>
    <script src="frontEnd/app/js_depl/bundle.js"></script>  
</body>
</html>
